### PR TITLE
Save rendered graphviz string as SVG

### PR DESCRIPTION
**Pull request by jparklev**
# WIP

eg
graph

### CODE REVIEW

**Comment by jparklev** [comment]
@xwvvvvwx

**Comment by d-xo** [comment]
oh nice!

FYI there is still some work to be done on getting all the auth connections into the graph. 

Also coloring the different connections as different colors.

**Comment by asymmetric** [comment]
Is there also a vector version, e.g. SVG?

**Comment by jparklev** [comment]
@xwvvvvwx Gotcha. Any thoughts on what the coloring should be based on? Edges colored by origin node?

@asymmetric Hmm yea, we’re not exporting it atm, but the approach here actually already generates an svg. Could totally expose that

**Comment by asymmetric** [comment]
@jparklev If it's not too much trouble, I think it would be useful. Even more than the PNG actually, cause that can be created from the SVG along with any other format.

**Comment by jparklev** [comment]
@asymmetric fair point, the default export should be in svg format now 🙂

**Comment by d-xo** [comment]
> @xwvvvvwx Gotcha. Any thoughts on what the coloring should be based on? Edges colored by origin node?

I would color by auth type. IIRC there are three kinds of auth connection in dss:

1. `rely` / `deny`
2. `dsAuth` (owner & authority)
3. `DSRoles` (`canCall`)

[This testcase](https://github.com/makerdao/dss-deploy/blob/master/src/DssDeploy.t.sol#L525) has a list of all the expected auth connections in `dss`.

**Pull request merged**
