### PR TITLE
refector deployment scripts

### PR DESCRIPTION
**Pull request by iamchrissmith**
refactor deployment scripts to integrate changes to dss-deploy and testchain-dss-deploy-scripts.  Moving towards more modular and hopefully CI/audit ready code

### CODE REVIEW

**Comment by iamchrissmith** [comment]
This should be ready to merge at this point. 

As a way of having async discussion around the 'missing contract': here is the graph that `step-1-deploy` this paints:

image

The node at the top that is just an address is a `LogSetAuthority` event, I believe from this [dss-deploy line](https://github.com/makerdao/dss-deploy/blob/master/src/DssDeploy.sol#L298) from testchain when [`base-deploy` calls on this line](https://github.com/makerdao/dss-deploy/blob/master/bin/deploy-core#L49) which passes in `$MCD_ADM` as the `authority` to be set.  However the event that is emitted does not contain the address of `$MCD_ADM` that gets reported out to `out/addresses.json`. 

My current theory is that [launching a new authority](https://github.com/makerdao/dss-deploy/blob/master/bin/deploy-core#L26) or [unsetting it](https://github.com/makerdao/testchain-dss-deployment-scripts/blob/master/scripts/base-deploy#L35) is not behaving as expected and there is an old `MCD_ADM` getting passed into the `pause`.

**Comment by iamchrissmith** [comment]
from @gbalabasquer:
```
so it is using a temporary ds-roles
as auth of the pause
so we do not need to do the previous trick of assigning MKR, and getting elected
it seemed cleaner doing this way
so as we do not previously define MCD_ADM, it is created: https://github.com/makerdao/dss-deploy/blob/master/bin/deploy-core#L26
Set of smart contracts and bash scripts to deploy Multi collateral DAI - makerdao/dss-deploy
then at the end of the tdds scripts we set the chief https://github.com/makerdao/testchain-dss-deployment-scripts/blob/master/step-1-deploy#L68
but we only replace it in the DSPause as the DssDeploy is useless at this point as we've released all the auth of the core contracts
```

**Comment by d-xo** [comment]
@iamchrissmith how is the chief owned by anything except the zero address? 

Unless I'm reading [this](https://github.com/dapphub/ds-chief/blob/master/src/chief.sol#L146) wrong it should only ever be owned by `0`?

**Comment by iamchrissmith** [comment]
I think you are correct; however, `DSAuth` [emits a `LogSetOwner` event](https://github.com/dapphub/ds-auth/blob/master/src/auth.sol#L33), so from the current implementation of the tool it only sees that event.  `DSChief` is not emitting any event so we don't pick up on that.  I outlined some tasks [here](https://github.com/makerdao/smart-contracts-team-pm/issues/195) that will help with this.  In particular:
- just getting the state of `owner` and `authority` at the end rather than relying on events
- having some manual checks for these un`emit`ted events in constructors (like this one as well as things like [setting `wards` in `dss`](https://github.com/makerdao/dss/blob/master/src/flap.sol#L79) that gonzalo pointed out)

**Pull request merged**
